version: "3"

services:
  back:
    image: back
    build: ./back
    command: gunicorn -b 0.0.0.0:80 app:api
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/back/*"
      VIRTUAL_HOST_WEIGHT: 10
      DB_HOST: db
      FILE_STORAGE: /run/files
    links:
      - db
    volumes:
      - file-storage:/run/files
    depends_on:
      - db

  files:
    image: files
    build: ./files
    command: gunicorn -b 0.0.0.0:80 app:api
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/files/*"
      VIRTUAL_HOST_WEIGHT: 10
      FILE_STORAGE: /run/files
    volumes:
      - file-storage:/run/files

  db:
    image: mongo:latest
    volumes:
      - database-storage:/run/db
    ports:
      - 27017:27017

  ui:
    image: ui
    build: ./ui
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/ui, */ui*"

  renderer:
    image: nginx
    volumes:
      - file-storage:/usr/share/nginx/html/renderer:ro
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/renderer*"

  lb:
    image: dockercloud/haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'
      - '1936:1936'
    links:
      - back
      - db
      - ui
      - files
      - renderer

volumes:
    file-storage:
    database-storage:
