version: "3"

services:
  db:
    image: mongo:latest
    volumes:
      - database-storage:/run/db
    ports:
      - 27017:27017

  learning_object_metadata_schema:
    image: learning_object_metadata_schema
    build: ./learning_object/metadata_schema
    command: gunicorn -b 0.0.0.0:80 app:api
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/learning-object-metadata-schema, */learning-object-metadata-schema/*"
      VIRTUAL_HOST_WEIGHT: 10
      DB_HOST: db
    links:
      - db
    depends_on:
      - db

  learning_object_file_manager:
    image: learning_object_file_manager
    build: ./learning_object/file_manager
    command: gunicorn -b 0.0.0.0:80 app:api
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/learning-object-file-manager, */learning-object-file-manager/*"
      VIRTUAL_HOST_WEIGHT: 10
      FILE_STORAGE: /run/files
    volumes:
      - file-storage:/run/files

  learning_object_default_files:
    image: learning_object_default_files
    build:
      context: ./learning_object/default_files
      dockerfile: Dockerfile
    volumes:
      - file-storage:/run/files

  learning_object_collection:
    image: learning_object_collection
    build: ./learning_object/collection
    command: gunicorn -b 0.0.0.0:80 app:api
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/learning-object-collection, */learning-object-collection/*"
      VIRTUAL_HOST_WEIGHT: 10
      DB_HOST: db
    links:
      - db
    depends_on:
      - learning_object_metadata_schema

  learning_object_file_renderer:
    image: nginx
    volumes:
      - file-storage:/usr/share/nginx/html/learning-object-file-renderer:ro
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/learning-object-file-renderer/*"

  user_collection:
    image: user_collection
    build: ./user/collection
    command: gunicorn -b 0.0.0.0:80 app:api
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/user-collection, */user-collection/*"
      VIRTUAL_HOST_WEIGHT: 10
      DB_HOST: db
    links:
      - db
    depends_on:
      - db

  user_login:
    image: user_login
    build: ./user/login
    command: gunicorn -b 0.0.0.0:80 app:api
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/user-login, */user-login/*"
      VIRTUAL_HOST_WEIGHT: 10
      DB_HOST: db
    links:
      - db
    depends_on:
      - db

  user_account_validation:
    image: user_account_validation
    build: ./user/account_validation
    command: gunicorn -b 0.0.0.0:80 app:api
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/user-account, */user-account/*"
      VIRTUAL_HOST_WEIGHT: 10
      DB_HOST: db
    links:
      - db
    depends_on:
      - db

  lb:
    image: dockercloud/haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'
      - '1936:1936'
    links:
      - db
      - learning_object_metadata_schema
      - learning_object_file_manager
      - learning_object_collection
      - learning_object_file_renderer
      - user_collection
      - user_login
      - user_account_validation

volumes:
    file-storage:
    database-storage:
